#prefix name should be autogenerated from the input bam rather than specifying in the input.json
task markduplicates {

    File input_bam
    String prefix

    Int memory
    Int disk_space
    Int num_threads
    Int num_preempt

    String output_bam = sub(basename(input_bam), "\\.bam$", ".md.bam")

    command {
        set -euo pipefail
        java -Xmx10g -jar src/picard/picard.jar  MarkDuplicates \
            I=${input_bam} \
            O= ${output_bam} \
            CREATE_INDEX=true \
            VALIDATION_STRINGENCY=SILENT \
            ASSUME_SORT_ORDER=coordinate \
            M=${prefix}.marked_dup_metrics.txt \
            REMOVE_DUPLICATES=false

        samtools index ${output_bam}
    }

    output {
        File bam_file = "${output_bam}"
        File bam_index = "${output_bam}.bai"
        File metrics = "${prefix}.marked_dup_metrics.txt"
    }

    runtime {
        docker: "gcr.io/broad-cga-francois-gtex/gtex_rnaseq:V8"
	memory: "${memory}GB"
        disks: "local-disk ${disk_space} HDD"
        cpu: "${num_threads}"
        preemptible: "${num_preempt}"
    }

    meta {
        author: "Archana Raja"
    }
}


workflow markduplicates_workflow {
    call markduplicates
}
