version 1.0

#prefix name should be autogenerated from the input bam rather than specifying in the input.json

task markduplicates {
    input {
        String SID
        File input_bam

        Int memory
        Int disk_space
        Int ncpu
        Int preemptible
        String docker
    }

    String output_bam = sub(basename(input_bam), "\\.bam$", ".md.bam")

    command <<<
        set -euo pipefail
        echo "--- $(date "+[%b %d %H:%M:%S]") Running ulimit ---"
        ulimit -c unlimited

        echo "--- $(date "+[%b %d %H:%M:%S]") Done with ulimit, running markduplicates ---"
        java -Xmx~{memory}g -jar /usr/local/bin/picard.jar  MarkDuplicates \
            I=~{input_bam} \
            O=~{output_bam} \
            VALIDATION_STRINGENCY=SILENT \
            ASSUME_SORT_ORDER=coordinate \
            M=~{SID}.marked_dup_metrics.txt \
            REMOVE_DUPLICATES=false

        echo "--- $(date "+[%b %d %H:%M:%S]") Done with markduplicates, finished task ---"
    >>>

    output {
        File metrics = "${SID}.marked_dup_metrics.txt"
    }

    runtime {
        cpu: ncpu
        memory: "${memory}GB"
        disks: "local-disk ${disk_space} HDD"
        docker: docker
        preemptible: preemptible
    }

    parameter_meta {
        SID: {
            type: "id"
        }
        input_bam: {
            label: "Mapped/Aligned Reads BAM File"
        }
    }

    meta {
        author: "Archana Raja"
    }
}
